title: Ravensport
description: Actionable Detection and Autonomous Mitigation of Cyber Attacks on Critical Infrastructure Networks. A competition at IEEE SaTML 2027.
theme: jekyll-theme-minimal
show_downloads: false
